### ISSUE TITLE
Ability to edit/delete the posts/comments of the current users and ones created by the user

### ISSUE THREAD

**Issue by snguyenthanh** [Ang-YC/kidsbook-app#16]

**Comment by Ang-YC** [comment]
Only superuser should be allowed to delete (it is actually hide instead of delete in database), unless you have a very good API design such that the backend return deleted posts and comments for superuser.

Edited comments should have edit history as well, which I don't even think our team have the time for that. It is necessary to include edit history to prevent cyberbullies from modifying it without people realising.
